{% set version = "24.1.0.20250822" %}

package:
  name: types-aiofiles
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-aiofiles/types_aiofiles-{{ version }}.tar.gz
  sha256: 9ab90d8e0c307fe97a7cf09338301e3f01a163e39f3b529ace82466355c84a7b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/aiofiles-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for aiofiles
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
