{% set name = "types-aiofiles" %}
{% set version = "24.1.0.20241221" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c40f6c290b0af9e902f7f3fa91213cf5bb67f37086fb21dc0ff458253586ad55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/aiofiles-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for aiofiles
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
